import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.scss';
import 'normalize.css';
import ThemeProvider from '@/components/ThemeProvider';

const font = localFont({
  src: '../font/PretendardVariable.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" className={font.className}>
      <body>
        <ThemeProvider defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
